### ISSUE TITLE
[EPIC] Lyrics

### ISSUE THREAD

**Issue by Artem3213212** [Alexandra2706/Opening-db#18]
- [ ] Создать таблицы в бд
- [ ] Добавить индекс для полнотекстового поиска
- [ ] Добавить фронт + кеширование
- [ ] Написать парсеры для сайтов с текстами и переводами
