### ISSUE TITLE
[EPIC] Фронт

### ISSUE THREAD

**Issue by Artem3213212** [Alexandra2706/Opening-db#6]
- [ ] Создать пустой проект на vue
- [ ] Создать CI/CD для сборки в бакет
- [ ] Купить домен
- [ ] Настроить Cloudflare
- [ ] Описать 2 домена в tf (`api` + `@`)
- [ ] Сделать главную страницу
- [ ] Сделать страницу поиска
- [ ] Сделать страницу анимэ
- [ ] Сделать страницу опенинга
- [ ] Сделать страницу франшизы
- [ ] Сделать страницу испольнитиеля
- [ ] Сделать страницу TrackSet'a (альбом, сингл и тд.)
- [ ] Подключить IPFS для фронта(картинки анимэ)
