### ISSUE TITLE
[EPIC] Структуры данных которые надо добавить в бд

### ISSUE THREAD

**Issue by Artem3213212** [Alexandra2706/Opening-db#7]
- [x] Анимэ
- [x] Картинка(IPFS Объект)
- [x] Видео(IPFS Объект)
- [ ] Аудио(IPFS Объект)
- [x] IPFS Объект
- [ ] Человек ака автор ака исполнитель (надо связь многие  ко многим с анимэ, вообщем всё как на шики)
- [ ] Track (конкретное произведение): название(может быть несколько) + опционально исполнитель(может быть несколько)
- [ ] TrackRole: Track + роль (OP, ED, OST, Other) + Серии в которых был + Анимэ
- [ ] TrackList: Тип (Album, Single, Other) + название(может быть несколько) + дата выхода + опционально исполнитель(может быть несколько) + список треков (упорядоченный)
- [ ] TrackRevision: track +Видео или Аудио + IsTVSized
